name: enzyme-pred-env

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - bokeh
  - cudatoolkit
  - datashader
  - git
  - ipywidgets
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-nvdashboard
  - jupyterlab-lsp
  - matplotlib
  - numba
  - numpy
  - pandas
  - pip
  - pip:
    - -r requirements.txt
  - python=3.7
  - pytorch
  - scikit-learn
  - scipy
  - tensorboard
  - torchaudio
  - torchmetrics
  - torchtext
  - torchvision
  - wandb

